"""Add student id column

Revision ID: 6661c5d6588c
Revises: 07b82f889002
Create Date: 2020-11-04 16:12:28.307073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6661c5d6588c'
down_revision = '07b82f889002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'student_id')
    # ### end Alembic commands ###
